### ISSUE TITLE
Prevent tooltip flickering

### ISSUE THREAD

**Issue by adamjohnson** [nico3333fr/van11y-accessible-simple-tooltip-aria#1]
## Steps to reproduce the issue

  1. Open the demo
  1. Hover over any of the three `<button>` elements.
  1. While doing so, move your cursor toward the arrow sticking out from the tooltip. Here's a photo illustrating where to hover:

![Hover anywhere in the yellow box to see the tooltip flicker](https://user-images.githubusercontent.com/575865/34051840-026decb8-e18e-11e7-9bb2-2cb83f831e8d.png)

## Results

The tooltip will get confused and flicker quickly. This strobe-like effect could cause seizures and violates the [Operable tenet of WCAG 2.0](https://www.w3.org/WAI/WCAG20/quickref/#seizure). 

## Expected results

The tooltip should not flash.

## Potential (not ideal) fix

Making `.simpletooltip` have a negative `z-index` prevents the flicker in your demo. I changed [line 172](https://github.com/nico3333fr/van11y-accessible-simple-tooltip-aria/blob/master/demo/styles.css#L172) of your CSS file to `z-index: -10`. 

This `z-index` change is not ideal because if you have multiple tooltips right after one-another (for example: a row of small icons), the tooltips won't show in front of the adjacent elements.

The root of this problem could likely be in the javascript.

### Environment

  1. OSX
  1. Tested in latest versions of Chrome, Firefox, and Opera.

**PS:** Thanks for making this! It's a neat little utility.

**Comment by yoanmalie** [comment]
By ading `pointer-event: none;` on the `::before` pseudo-element of  the `<span class="simpletooltip js-simple-tooltip">` it work.
I can send a PR if you're ok with this solution.

**Comment by nico3333fr** [comment]
@yoanmalie hey, this is a good idea and seems to work from my side. 👍 

@adamjohnson do you confirm that it fixes the problm on your side?

**Comment by nico3333fr** [comment]
Fine, I've merged the PR. Other comment on Twitter told me that the flickering comes from the style for the triangle, it might be useful to create it with a transform (and not using border as I did)

Thanks to all ;)

**Comment by adamjohnson** [comment]
Looking good folks! I added this to my project. 

Something of note: the tooltip will still flicker in the demo if you shrink your window to a mobile size where the text in the button is on two lines. This can be alleviated by adding `display: block;` to `.simpletooltip_container, .minimalist-simpletooltip_container, .minimalist-left-simpletooltip_container`. Not sure if adding this is wise or not, but I thought I would mention it for future visitors. 

___________________________

Thanks for the quick response. I hadn't used `pointer-events` before, so that's educational.
